apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sso.fullname" . }}
  labels:
    app: {{ template "sso.name" . }}
    chart: {{ template "sso.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sso.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sso.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: {{ .Values.envs.var1}}
            value: "{{ .Release.Name }}-{{ .Values.envs.var1Value }}"
          - name: {{ .Values.envs.var2}}
            value: "{{ .Release.Name }}-{{ .Values.envs.var2Value}}"
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort}}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
          volumeMounts:
           - mountPath: {{ .Values.persistent.containerPath}}
             name: {{ .Values.persistent.volumeName}}
      volumes:
       - name: {{ .Values.persistent.volumeName}}
         persistentVolumeClaim: 
           claimName: {{ .Values.persistent.claimName}}

